version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: samuro
    environment:
      - POSTGRES_DB=samuro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3228
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres-data: